import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Footer } from '@/components/footer';
import { Navbar } from '@/components/navbar';
import Link from 'next/link';
import Image from 'next/image';
import logo from '../../../public/images/logo_dual_color.svg';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Transmídia',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <body
        className={cn(
          `flex flex-col min-h-screen bg-[#FCFAEC] text-black`,
          inter.className,
        )}
      >
        <header className='p-6 flex justify-center items-center bg-[#2D2D2D]'>
          <Link href='/'>
            <Image src={logo} alt='Transmídia' />
          </Link>
        </header>
        {children}

        <Footer />
        <Navbar />
      </body>
    </html>
  );
}
